pipeline{
    agent any
    stages{
        stage("Build Frontend"){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/LudwingCabello/Pep1-Tingeso']])
                dir("newapp"){
                    bat "npm install"
                    bat "npm run build"
                }
            }
        }
        stage("Build and Push Docker Image"){
            steps{
                dir("newapp"){
                    script{
                         withDockerRegistry(credentialsId: 'docker-credentials'){
                            bat "docker build -t ludwingcabello/pep1tingeso-front ."
                            bat "docker push ludwingcabello/pep1tingeso-front"
                        }
                    }                    
                }
            }
        }
    }
}
